CREATE TABLE board (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  tag INT UNSIGNED NOT NULL,
  content BLOB NOT NULL,
  time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
) ENGINE = InnoDB charset = utf8;